import { useTheme } from "@/ThemeContext";
import { useColorScheme, StyleSheet } from "react-native";

export const colors = {
    charcol90: "#3D3D3D",
    charcol40: "#888888",
    charcol50: "#6D6D6D",
    charcol20: "#D1D1D1",
    charcol30: "#B0B0B0",
    charcol60: "#5D5D5D",
    charcol05: "#F6F6F6",
    charcol10: "#E7E7E7",
    charcol100: "#2C2C2C",
    charcol80: "#454545",
    white: "#FFFFFF",
    purple40: "#934DFF",
    purple10: "#EEE7FF",
    purple50: "#934DFF",
    purple60: "#8929FF",
    purple05: "#F5F2FF",
    red: "#FF5151",
    black: "#000000",
    orange: "#FF5C5C",
    green: "#62E384",
    purple: "#9E9EFF",
    lightPurple: "#E3CCFF",
    lightPurple2: "#F8F5FF",
    skyblue: "#99B8FF",
    darkpurple: "#8787FF"
};


// Define the color themes (light and dark)
export const color = {
    light: {
        background: "#FFFFFF", // White background for light mode
        textPrimary: "#2C2C2C", // charcol100
        textSecondary: "#888888", // charcol40
        charcol90: "#3D3D3D",
        charcol40: "#888888",
        charcol50: "#6D6D6D",
        charcol20: "#D1D1D1",
        charcol30: "#B0B0B0",
        charcol60: "#5D5D5D",
        charcol05: "#F6F6F6",
        charcol10: "#E7E7E7",
        charcol100: "#2C2C2C",
        charcol80: "#454545",
        white: "#FFFFFF",
        purple40: "#934DFF",
        purple10: "#EEE7FF",
        purple50: "#934DFF",
        purple60: "#8929FF",
        purple05: "#F5F2FF",
        red: "#FF5151",
        black: "#000000",
        orange: "#FF5C5C",
        green: "#62E384",
        purple: "#9E9EFF",
        lightPurple: "#E3CCFF",
        lightPurple2: "#F8F5FF",
        skyblue: "#99B8FF",
        darkpurple: "#8787FF",
    },
    dark: {
        background: "#2C2C2C", // Dark background for dark mode
        textPrimary: "#FFFFFF", // White for primary text
        textSecondary: "#B0B0B0", // charcol30
        charcol90: "#ffff",
        charcol40: "#888888",
        charcol50: "#D1D1D1",
        charcol20: "#D1D1D1",
        charcol30: "#B0B0B0",
        charcol60: "#5D5D5D",
        charcol05: "#F6F6F6",
        charcol10: "#E7E7E7",
        charcol100: "#ffffff",
        charcol80: "#454545",
        white: "#FFFFFF",
        purple40: "#934DFF",
        purple10: "#EEE7FF",
        purple50: "#934DFF",
        purple60: "#8929FF",
        purple05: "#F5F2FF",
        red: "#FF5151",
        black: "#000000",
        orange: "#FF5C5C",
        green: "#62E384",
        purple: "#9E9EFF",
        lightPurple: "#E3CCFF",
        lightPurple2: "#F8F5FF",
        skyblue: "#99B8FF",
        darkpurple: "#8787FF",
    },
};

// Define the global styles
export const getGlobalStyles = () => {
    const { isDarkMode } = useTheme();
    const theme = isDarkMode ? color.dark : color.light;

    return StyleSheet.create({
        container: {
            backgroundColor: theme.background,
            paddingHorizontal: 20,
        },
        heading_3: {
            fontSize: 22,
            fontWeight: "700",
            color: theme.charcol90,
        },
        border: {
            borderColor: theme.charcol10,
            borderWidth: 1,
        },
        // Text 10px
        text_10_reg_40: {
            fontFamily: "Inter_18pt-Regular",
            fontSize: 10,
            fontWeight: "400",
            lineHeight: 19.2,
            color: theme.charcol40,
        },
        // Text 12px
        text_12_reg_50: {
            fontFamily: "Inter_18pt-Regular",
            fontSize: 12,
            fontWeight: "400",
            lineHeight: 19.2,
            color: theme.charcol50,
        },
        text_12_reg_90: {
            fontFamily: "Inter_18pt-Regular",
            fontSize: 12,
            fontWeight: "400",
            lineHeight: 19.2,
            color: theme.charcol90,
        },
        text_12_reg_30: {
            fontFamily: "Inter_18pt-Regular",
            fontSize: 12,
            fontWeight: "400",
            lineHeight: 19.2,
            color: theme.charcol30,
        },
        text_12_reg_40: {
            fontFamily: "Inter_18pt-Regular",
            fontSize: 12,
            fontWeight: "400",
            lineHeight: 19.2,
            color: theme.textSecondary,
        },
        text_12_reg_pur50: {
            fontFamily: "Inter_18pt-Regular",
            fontSize: 12,
            fontWeight: "400",
            lineHeight: 19.2,
            color: theme.purple40,
        },
        text_12_reg_white: {
            fontFamily: "Inter_18pt-Regular",
            fontSize: 12,
            fontWeight: "400",
            lineHeight: 19.2,
            color: theme.white,
        },
        text_12_med_pur50: {
            fontFamily: "Inter_18pt-Medium",
            fontSize: 12,
            fontWeight: "500",
            lineHeight: 19.2,
            color: theme.purple40,
        },
        text_12_med_90: {
            fontFamily: "Inter_18pt-Medium",
            fontSize: 12,
            fontWeight: "500",
            lineHeight: 19.2,
            color: theme.textPrimary,
        },
        // Text 14px
        text_14_reg_white: {
            fontFamily: "Inter_18pt-Regular",
            fontSize: 14,
            fontWeight: "400",
            lineHeight: 21.56,
            color: theme.white,
        },
        text_14_reg_50: {
            fontFamily: "Inter_18pt-Regular",
            fontSize: 14,
            fontWeight: "400",
            lineHeight: 21.56,
            color: theme.charcol50,
        },
        text_14_reg_60: {
            fontFamily: "Inter_18pt-Regular",
            fontSize: 14,
            fontWeight: "400",
            lineHeight: 21.56,
            color: theme.charcol60,
        },
        text_14_reg_100: {
            fontFamily: "Inter_18pt-Regular",
            fontSize: 14,
            fontWeight: "400",
            lineHeight: 21.56,
            color: theme.charcol100,
        },
        text_14_reg_90: {
            fontFamily: "Inter_18pt-Regular",
            fontSize: 14,
            fontWeight: "400",
            lineHeight: 21.56,
            color: theme.textPrimary,
        },
        text_14_reg_40: {
            fontFamily: "Inter_18pt-Regular",
            fontSize: 14,
            fontWeight: "400",
            lineHeight: 21.56,
            color: theme.textSecondary,
        },
        text_14_med_90: {
            fontFamily: "Inter_18pt-Medium",
            fontSize: 14,
            fontWeight: "500",
            lineHeight: 21.56,
            color: theme.textPrimary,
        },
        text_14_reg_pur50: {
            fontFamily: "Inter_18pt-Regular",
            fontSize: 14,
            fontWeight: "400",
            lineHeight: 21.56,
            color: theme.purple40,
        },
        text_14_bold_pur50: {
            fontFamily: "Inter_18pt-Bold",
            fontSize: 14,
            fontWeight: "700",
            lineHeight: 21.56,
            color: theme.purple40,
        },
        text_14_bold_90: {
            fontFamily: "Inter_18pt-Bold",
            fontSize: 14,
            fontWeight: "700",
            lineHeight: 21.56,
            color: theme.textPrimary,
        },
        text_14_bold_40: {
            fontFamily: "Inter_18pt-Bold",
            fontSize: 14,
            fontWeight: "700",
            lineHeight: 21.56,
            color: theme.textSecondary,
        },
        text_14_bold_orange: {
            fontFamily: "Inter_18pt-Bold",
            fontSize: 14,
            fontWeight: "700",
            lineHeight: 21.56,
            color: theme.orange,
        },
        text_14_reg_orange: {
            fontFamily: "Inter_18pt-Regular",
            fontSize: 14,
            fontWeight: "400",
            lineHeight: 21.56,
            color: theme.red,
        },
        text_14_med_40: {
            fontFamily: "Inter_18pt-Medium",
            fontSize: 14,
            fontWeight: "500",
            lineHeight: 21.56,
            color: theme.textSecondary,
        },
        text_14_bold_100: {
            fontFamily: "Inter_18pt-Bold",
            fontSize: 14,
            fontWeight: "700",
            lineHeight: 19.2,
            color: theme.charcol100,
        },
        text_14_semi_90: {
            fontFamily: "Inter_18pt-SemiBold",
            fontSize: 14,
            fontWeight: "600",
            lineHeight: 21.6,
            color: theme.textPrimary,
        },
        // Text 16px
        text_16_med_90: {
            fontFamily: "Inter_18pt-Medium",
            fontSize: 16,
            fontWeight: "500",
            lineHeight: 19.2,
            color: theme.textPrimary,
        },
        text_16_bold_100: {
            fontFamily: "Inter_18pt-Bold",
            fontSize: 16,
            fontWeight: "700",
            lineHeight: 19.2,
            color: theme.charcol100,
        },
        text_16_bold_90: {
            fontFamily: "Inter_18pt-Bold",
            fontSize: 16,
            fontWeight: "700",
            lineHeight: 19.2,
            color: theme.textPrimary,
        },
        text_16_bold_80: {
            fontFamily: "Inter_18pt-Bold",
            fontSize: 16,
            fontWeight: "700",
            lineHeight: 19.2,
            color: theme.charcol80,
        },
        text_16_med_40: {
            fontFamily: "Inter_18pt-Medium",
            fontSize: 16,
            fontWeight: "500",
            lineHeight: 19.2,
            color: theme.textSecondary,
        },
        text_16_med_white: {
            fontFamily: "Inter_18pt-Medium",
            fontSize: 16,
            fontWeight: "500",
            lineHeight: 19.2,
            color: theme.white,
        },
        text_16_med_100: {
            fontFamily: "Inter_18pt-Medium",
            fontSize: 16,
            fontWeight: "500",
            lineHeight: 19.2,
            color: theme.charcol100,
        },
        text_16_reg_50: {
            fontFamily: "Inter_18pt-Regular",
            fontSize: 16,
            fontWeight: "400",
            lineHeight: 25.6,
            color: theme.charcol50,
        },
        text_16_reg_40: {
            fontFamily: "Inter_18pt-Regular",
            fontSize: 16,
            fontWeight: "400",
            lineHeight: 25.6,
            color: theme.textSecondary,
        },
        text_16_reg_100: {
            fontFamily: "Inter_18pt-Regular",
            fontSize: 16,
            fontWeight: "400",
            lineHeight: 25.6,
            color: theme.charcol100,
        },
        // Text 18px
        text_18_reg_90: {
            fontFamily: "Inter_18pt-Regular",
            fontSize: 18,
            fontWeight: "400",
            lineHeight: 21.6,
            color: theme.textPrimary,
        },
        text_18_semi_90: {
            fontFamily: "Inter_18pt-SemiBold",
            fontSize: 18,
            fontWeight: "600",
            lineHeight: 21.6,
            color: theme.textPrimary,
        },
        // Text 20px
        text_20_bold_90: {
            fontFamily: "Inter_18pt-Bold",
            fontSize: 20,
            fontWeight: "700",
            lineHeight: 24,
            color: theme.charcol100,
        },
        // Text 22px
        text_22_bold_90: {
            fontFamily: "Inter_18pt-Bold",
            fontSize: 22,
            fontWeight: "700",
            lineHeight: 26.4,
            color: theme.textPrimary,
        },
        text_22_reg_40: {
            fontFamily: "Inter_18pt-Regular",
            fontSize: 22,
            fontWeight: "400",
            lineHeight: 26.4,
            color: theme.textSecondary,
        },
        // Text 24px
        text_24_bold_100: {
            fontFamily: "Inter_18pt-Bold",
            fontSize: 24,
            fontWeight: "700",
            lineHeight: 28.8,
            color: theme.charcol100,
        },
        text_24_bold_90: {
            fontFamily: "Inter_18pt-Bold",
            fontSize: 24,
            fontWeight: "700",
            lineHeight: 28.8,
            color: theme.textPrimary,
        },
        text_24_bold_90_popins: {
            fontFamily: "Poppins-Bold",
            fontSize: 24,
            fontWeight: "700",
            lineHeight: 28.8,
            color: theme.textPrimary,
        },
        text_24_bold_100_popins: {
            fontFamily: "Poppins-Bold",
            fontSize: 24,
            fontWeight: "700",
            lineHeight: 28.8,
            color: theme.charcol100,
        },
        // Text 28px
        text_28_bold_90: {
            fontFamily: "Inter_18pt-Bold",
            fontSize: 28,
            fontWeight: "700",
            lineHeight: 28.8,
            color: theme.textPrimary,
        },
        text_28_bold_90_popins: {
            fontFamily: "Poppins-Bold",
            fontSize: 28,
            fontWeight: "700",
            lineHeight: 28.8,
            color: theme.textPrimary,
        },
        // Text 32px
        text_32_bold_90: {
            fontFamily: "Poppins-Bold",
            fontSize: 32,
            fontWeight: "700",
            lineHeight: 38.4,
            color: theme.textPrimary,
        },
        // Text 40px
        text_40_bold_90: {
            fontFamily: "Inter_18pt-Bold",
            fontSize: 40,
            fontWeight: "700",
            lineHeight: 40,
            color: theme.textPrimary,
        },
    });
};

